### PR TITLE
Move to fog-dynect 0.2.0 and update other gems

### PR DESCRIPTION
**Pull request by charlescng**
* Move fog-dynect to 0.2.0
* Update other gems

### CODE REVIEW

**Comment by etiennebarrie** [comment]
This is the diff, can the fact that it now includes `ttl` be a problem for us?
https://github.com/fog/fog-dynect/compare/v0.1.0...v0.2.0

**Comment by etiennebarrie** [comment]
It looks like we're using [`get_all_records` directly](https://github.com/Shopify/record_store/blob/master/lib/record_store/provider/dynect.rb#L47), which is the same thing that [`Fog::DNS::Dynect::Records.all`](https://github.com/fog/fog-dynect/blob/v0.2.0/lib/fog/dynect/models/dns/records.rb#L14) uses, but we're just going around it. So we may be able to use that now, but that shouldn't break anything.

**Comment by charlescng** [comment]
I've forgotten about this. A new commit to address:
image

**Comment by albiere** [comment]
We don't seem to use `:ttl => record['ttl']`, which has been added to the 0.2 version. We only use the `rdata` as seen here: https://github.com/Shopify/record_store/blob/master/lib/record_store/provider/dynect.rb#L88

**Pull request merged**
